
import React, { createContext, useState, useContext, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  isRTL: boolean;
  availableLanguages: { code: string; name: string; flag: string }[];
}

const translations = {
  en: {
    title: 'AI Call Bot',
    subtitle: 'Automate customer service',
    features: 'Features',
    products: 'Products',
    solutions: 'Solutions',
    resources: 'Resources',
    pricing: 'Pricing',
    about: 'About',
    contact: 'Contact',
    getStarted: 'Get Started',
    businessRegistration: 'Business Registration',
    registrationDescription: 'Register your business to start using our AI Call Bot',
    businessDetails: 'Business Details',
    adminAccount: 'Admin Account',
    employeeAccess: 'Employee Access',
    businessName: 'Business Name',
    industry: 'Industry',
    businessAddress: 'Business Address',
    phoneNumber: 'Phone Number',
    website: 'Website',
    optional: 'optional',
    businessDescription: 'Business Description',
    enterBusinessName: 'Enter your business name',
    enterIndustry: 'Enter your industry',
    enterAddress: 'Enter your business address',
    enterPhone: 'Enter your phone number',
    describeYourBusiness: 'Describe what your business does',
    briefDescriptionBusiness: 'A brief description of what your business does',
    adminName: 'Admin Name',
    adminEmail: 'Admin Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    enterFullName: 'Enter your full name',
    thisWillBeUsername: 'This will be your username to login',
    enterPassword: 'Enter a strong password',
    addEmployeeAccounts: 'Add Employee Accounts',
    employeeAccountsDescription: 'Add staff members who will have access to the system',
    employeeName: 'Employee Name',
    employeeRole: 'Employee Role',
    employeeEmail: 'Employee Email',
    temporaryPassword: 'Temporary Password',
    addEmployee: 'Add Employee',
    addedEmployees: 'Added Employees',
    noEmployeesAdded: 'No employees added yet',
    employee: 'Employee',
    remove: 'Remove',
    previous: 'Previous',
    next: 'Next',
    completeRegistration: 'Complete Registration',
    dashboard: 'Dashboard',
    callResolutionRate: 'Call Resolution Rate',
    callsHandledToday: 'Calls Handled Today',
    averageSatisfaction: 'Average Satisfaction',
    dashboardPlaceholder: 'Your full dashboard would appear here after registration',
    assistantGuide: 'Registration Assistant',
    hereToHelpRegister: 'I\'m here to help you register your business',
    guideWelcome: 'Welcome! I\'ll guide you through the registration process for your business.',
    guideBusinessInfo: 'First, you\'ll need to provide your business details like name, address, and contact information.',
    guideAdminAccount: 'Next, create an admin account that will have full access to manage your AI Call Bot system.',
    guideEmployeeAccess: 'Finally, you can add employee accounts for staff members who need access to the system.',
    guideCompletion: 'Once you\'ve completed all steps, you\'ll have immediate access to your AI Call Bot dashboard!',
    needHelp: 'I need help with a specific field',
    readyToStart: 'I\'m ready to get started',
    registrationSuccess: 'Registration successful!',
    redirectingToDashboard: 'Redirecting to your dashboard...'
  },
  es: {
    title: 'Bot de Llamadas IA',
    subtitle: 'Automatiza la atención al cliente',
    features: 'Características',
    products: 'Productos',
    solutions: 'Soluciones',
    resources: 'Recursos',
    pricing: 'Precios',
    about: 'Nosotros',
    contact: 'Contacto',
    getStarted: 'Comenzar',
    businessRegistration: 'Registro de Empresa',
    registrationDescription: 'Registre su empresa para comenzar a usar nuestro Bot de Llamadas IA',
    businessDetails: 'Detalles de la Empresa',
    adminAccount: 'Cuenta de Administrador',
    employeeAccess: 'Acceso de Empleados',
    businessName: 'Nombre de la Empresa',
    industry: 'Industria',
    businessAddress: 'Dirección de la Empresa',
    phoneNumber: 'Número de Teléfono',
    website: 'Sitio Web',
    optional: 'opcional',
    businessDescription: 'Descripción del Negocio',
    enterBusinessName: 'Ingrese el nombre de su empresa',
    enterIndustry: 'Ingrese su industria',
    enterAddress: 'Ingrese la dirección de su empresa',
    enterPhone: 'Ingrese su número de teléfono',
    describeYourBusiness: 'Describa a qué se dedica su empresa',
    briefDescriptionBusiness: 'Una breve descripción de a qué se dedica su empresa',
    adminName: 'Nombre del Administrador',
    adminEmail: 'Email del Administrador',
    password: 'Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    enterFullName: 'Ingrese su nombre completo',
    thisWillBeUsername: 'Este será su nombre de usuario para iniciar sesión',
    enterPassword: 'Ingrese una contraseña fuerte',
    addEmployeeAccounts: 'Agregar Cuentas de Empleados',
    employeeAccountsDescription: 'Agregue miembros del personal que tendrán acceso al sistema',
    employeeName: 'Nombre del Empleado',
    employeeRole: 'Rol del Empleado',
    employeeEmail: 'Email del Empleado',
    temporaryPassword: 'Contraseña Temporal',
    addEmployee: 'Agregar Empleado',
    addedEmployees: 'Empleados Agregados',
    noEmployeesAdded: 'Aún no se han agregado empleados',
    employee: 'Empleado',
    remove: 'Eliminar',
    previous: 'Anterior',
    next: 'Siguiente',
    completeRegistration: 'Completar Registro',
    dashboard: 'Panel de Control',
    callResolutionRate: 'Tasa de Resolución de Llamadas',
    callsHandledToday: 'Llamadas Atendidas Hoy',
    averageSatisfaction: 'Satisfacción Promedio',
    dashboardPlaceholder: 'Su panel de control completo aparecería aquí después del registro',
    assistantGuide: 'Asistente de Registro',
    hereToHelpRegister: 'Estoy aquí para ayudarle a registrar su empresa',
    guideWelcome: '¡Bienvenido! Le guiaré a través del proceso de registro para su empresa.',
    guideBusinessInfo: 'Primero, deberá proporcionar los detalles de su empresa como nombre, dirección e información de contacto.',
    guideAdminAccount: 'A continuación, cree una cuenta de administrador que tendrá acceso completo para administrar su sistema de Bot de Llamadas IA.',
    guideEmployeeAccess: 'Finalmente, puede agregar cuentas de empleados para los miembros del personal que necesiten acceso al sistema.',
    guideCompletion: '¡Una vez que haya completado todos los pasos, tendrá acceso inmediato a su panel de control de Bot de Llamadas IA!',
    needHelp: 'Necesito ayuda con un campo específico',
    readyToStart: 'Estoy listo para comenzar',
    registrationSuccess: '¡Registro exitoso!',
    redirectingToDashboard: 'Redirigiendo a su panel de control...'
  },
  fr: {
    title: 'Robot d\'Appel IA',
    subtitle: 'Automatisez le service client',
    features: 'Fonctionnalités',
    products: 'Produits',
    solutions: 'Solutions',
    resources: 'Ressources',
    pricing: 'Tarifs',
    about: 'À propos',
    contact: 'Contact',
    getStarted: 'Commencer',
    businessRegistration: 'Enregistrement d\'Entreprise',
    registrationDescription: 'Enregistrez votre entreprise pour commencer à utiliser notre Robot d\'Appel IA',
    businessDetails: 'Détails de l\'Entreprise',
    adminAccount: 'Compte Administrateur',
    employeeAccess: 'Accès Employés',
    businessName: 'Nom de l\'Entreprise',
    industry: 'Secteur d\'Activité',
    businessAddress: 'Adresse de l\'Entreprise',
    phoneNumber: 'Numéro de Téléphone',
    website: 'Site Web',
    optional: 'optionnel',
    businessDescription: 'Description de l\'Entreprise',
    enterBusinessName: 'Entrez le nom de votre entreprise',
    enterIndustry: 'Entrez votre secteur d\'activité',
    enterAddress: 'Entrez l\'adresse de votre entreprise',
    enterPhone: 'Entrez votre numéro de téléphone',
    describeYourBusiness: 'Décrivez l\'activité de votre entreprise',
    briefDescriptionBusiness: 'Une brève description de l\'activité de votre entreprise',
    adminName: 'Nom de l\'Administrateur',
    adminEmail: 'Email de l\'Administrateur',
    password: 'Mot de Passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    enterFullName: 'Entrez votre nom complet',
    thisWillBeUsername: 'Ce sera votre nom d\'utilisateur pour vous connecter',
    enterPassword: 'Entrez un mot de passe fort',
    addEmployeeAccounts: 'Ajouter des Comptes Employés',
    employeeAccountsDescription: 'Ajoutez des membres du personnel qui auront accès au système',
    employeeName: 'Nom de l\'Employé',
    employeeRole: 'Rôle de l\'Employé',
    employeeEmail: 'Email de l\'Employé',
    temporaryPassword: 'Mot de Passe Temporaire',
    addEmployee: 'Ajouter un Employé',
    addedEmployees: 'Employés Ajoutés',
    noEmployeesAdded: 'Aucun employé ajouté pour l\'instant',
    employee: 'Employé',
    remove: 'Supprimer',
    previous: 'Précédent',
    next: 'Suivant',
    completeRegistration: 'Terminer l\'Enregistrement',
    dashboard: 'Tableau de Bord',
    callResolutionRate: 'Taux de Résolution d\'Appels',
    callsHandledToday: 'Appels Traités Aujourd\'hui',
    averageSatisfaction: 'Satisfaction Moyenne',
    dashboardPlaceholder: 'Votre tableau de bord complet apparaîtrait ici après l\'enregistrement',
    assistantGuide: 'Assistant d\'Enregistrement',
    hereToHelpRegister: 'Je suis là pour vous aider à enregistrer votre entreprise',
    guideWelcome: 'Bienvenue ! Je vais vous guider à travers le processus d\'enregistrement de votre entreprise.',
    guideBusinessInfo: 'D\'abord, vous devrez fournir les détails de votre entreprise comme le nom, l\'adresse et les coordonnées.',
    guideAdminAccount: 'Ensuite, créez un compte administrateur qui aura un accès complet pour gérer votre système de Robot d\'Appel IA.',
    guideEmployeeAccess: 'Enfin, vous pouvez ajouter des comptes employés pour les membres du personnel qui ont besoin d\'accéder au système.',
    guideCompletion: 'Une fois que vous aurez terminé toutes les étapes, vous aurez un accès immédiat à votre tableau de bord du Robot d\'Appel IA !',
    needHelp: 'J\'ai besoin d\'aide pour un champ spécifique',
    readyToStart: 'Je suis prêt à commencer',
    registrationSuccess: 'Enregistrement réussi !',
    redirectingToDashboard: 'Redirection vers votre tableau de bord...'
  },
  hi: {
    title: 'AI कॉल बॉट',
    subtitle: 'ग्राहक सेवा स्वचालित करें',
    features: 'विशेषताएं',
    products: 'उत्पाद',
    solutions: 'समाधान',
    resources: 'संसाधन',
    pricing: 'मूल्य निर्धारण',
    about: 'हमारे बारे में',
    contact: 'संपर्क करें',
    getStarted: 'शुरू करें',
    businessRegistration: 'व्यापार पंजीकरण',
    registrationDescription: 'हमारे AI कॉल बॉट का उपयोग शुरू करने के लिए अपने व्यवसाय को पंजीकृत करें',
    businessDetails: 'व्यवसाय विवरण',
    adminAccount: 'व्यवस्थापक खाता',
    employeeAccess: 'कर्मचारी पहुंच',
    businessName: 'व्यवसाय का नाम',
    industry: 'उद्योग',
    businessAddress: 'व्यवसाय का पता',
    phoneNumber: 'फ़ोन नंबर',
    website: 'वेबसाइट',
    optional: 'वैकल्पिक',
    businessDescription: 'व्यवसाय विवरण',
    enterBusinessName: 'अपने व्यवसाय का नाम दर्ज करें',
    enterIndustry: 'अपना उद्योग दर्ज करें',
    enterAddress: 'अपने व्यवसाय का पता दर्ज करें',
    enterPhone: 'अपना फोन नंबर दर्ज करें',
    describeYourBusiness: 'बताएं कि आपका व्यवसाय क्या करता है',
    briefDescriptionBusiness: 'आपका व्यवसाय क्या करता है इसका संक्षिप्त विवरण',
    adminName: 'व्यवस्थापक का नाम',
    adminEmail: 'व्यवस्थापक ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    thisWillBeUsername: 'यह लॉगिन करने के लिए आपका उपयोगकर्ता नाम होगा',
    enterPassword: 'एक मजबूत पासवर्ड दर्ज करें',
    addEmployeeAccounts: 'कर्मचारी खाते जोड़ें',
    employeeAccountsDescription: 'उन स्टाफ सदस्यों को जोड़ें जिन्हें सिस्टम तक पहुंच की आवश्यकता होगी',
    employeeName: 'कर्मचारी का नाम',
    employeeRole: 'कर्मचारी की भूमिका',
    employeeEmail: 'कर्मचारी का ईमेल',
    temporaryPassword: 'अस्थायी पासवर्ड',
    addEmployee: 'कर्मचारी जोड़ें',
    addedEmployees: 'जोड़े गए कर्मचारी',
    noEmployeesAdded: 'अभी तक कोई कर्मचारी नहीं जोड़ा गया',
    employee: 'कर्मचारी',
    remove: 'हटाएं',
    previous: 'पिछला',
    next: 'अगला',
    completeRegistration: 'पंजीकरण पूरा करें',
    dashboard: 'डैशबोर्ड',
    callResolutionRate: 'कॉल समाधान दर',
    callsHandledToday: 'आज संभाले गए कॉल',
    averageSatisfaction: 'औसत संतुष्टि',
    dashboardPlaceholder: 'पंजीकरण के बाद आपका पूर्ण डैशबोर्ड यहां दिखाई देगा',
    assistantGuide: 'पंजीकरण सहायक',
    hereToHelpRegister: 'मैं आपके व्यवसाय को पंजीकृत करने में आपकी सहायता के लिए यहां हूं',
    guideWelcome: 'स्वागत है! मैं आपको अपने व्यवसाय के लिए पंजीकरण प्रक्रिया के माध्यम से मार्गदर्शन करूंगा।',
    guideBusinessInfo: 'सबसे पहले, आपको अपने व्यवसाय के विवरण जैसे नाम, पता और संपर्क जानकारी प्रदान करनी होगी।',
    guideAdminAccount: 'इसके बाद, एक व्यवस्थापक खाता बनाएं जिसे आपके AI कॉल बॉट सिस्टम को प्रबंधित करने के लिए पूर्ण पहुंच होगी।',
    guideEmployeeAccess: 'अंत में, आप उन कर्मचारियों के लिए कर्मचारी खाते जोड़ सकते हैं जिन्हें सिस्टम तक पहुंच की आवश्यकता है।',
    guideCompletion: 'सभी चरणों को पूरा करने के बाद, आपको अपने AI कॉल बॉट डैशबोर्ड तक तुरंत पहुंच मिल जाएगी!',
    needHelp: 'मुझे किसी विशिष्ट फ़ील्ड के लिए सहायता चाहिए',
    readyToStart: 'मैं शुरू करने के लिए तैयार हूं',
    registrationSuccess: 'पंजीकरण सफल!',
    redirectingToDashboard: 'आपके डैशबोर्ड पर पुनर्निर्देशित किया जा रहा है...'
  },
  ar: {
    title: 'روبوت مكالمات الذكاء الاصطناعي',
    subtitle: 'أتمتة خدمة العملاء',
    features: 'المميزات',
    products: 'المنتجات',
    solutions: 'الحلول',
    resources: 'الموارد',
    pricing: 'التسعير',
    about: 'عن الشركة',
    contact: 'اتصل بنا',
    getStarted: 'ابدأ الآن',
    businessRegistration: 'تسجيل الشركة',
    registrationDescription: 'سجل شركتك للبدء في استخدام روبوت المكالمات الذكي',
    businessDetails: 'تفاصيل الشركة',
    adminAccount: 'حساب المسؤول',
    employeeAccess: 'وصول الموظفين',
    businessName: 'اسم الشركة',
    industry: 'الصناعة',
    businessAddress: 'عنوان الشركة',
    phoneNumber: 'رقم الهاتف',
    website: 'الموقع الإلكتروني',
    optional: 'اختياري',
    businessDescription: 'وصف الشركة',
    enterBusinessName: 'أدخل اسم شركتك',
    enterIndustry: 'أدخل مجال عملك',
    enterAddress: 'أدخل عنوان شركتك',
    enterPhone: 'أدخل رقم هاتفك',
    describeYourBusiness: 'صف ما تقوم به شركتك',
    briefDescriptionBusiness: 'وصف موجز لما تقوم به شركتك',
    adminName: 'اسم المسؤول',
    adminEmail: 'البريد الإلكتروني للمسؤول',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    enterFullName: 'أدخل اسمك الكامل',
    thisWillBeUsername: 'سيكون هذا اسم المستخدم الخاص بك لتسجيل الدخول',
    enterPassword: 'أدخل كلمة مرور قوية',
    addEmployeeAccounts: 'إضافة حسابات الموظفين',
    employeeAccountsDescription: 'أضف أعضاء الفريق الذين سيحتاجون إلى الوصول إلى النظام',
    employeeName: 'اسم الموظف',
    employeeRole: 'دور الموظف',
    employeeEmail: 'البريد الإلكتروني للموظف',
    temporaryPassword: 'كلمة مرور مؤقتة',
    addEmployee: 'إضافة موظف',
    addedEmployees: 'الموظفون المضافون',
    noEmployeesAdded: 'لم تتم إضافة موظفين حتى الآن',
    employee: 'موظف',
    remove: 'إزالة',
    previous: 'السابق',
    next: 'التالي',
    completeRegistration: 'إكمال التسجيل',
    dashboard: 'لوحة التحكم',
    callResolutionRate: 'معدل حل المكالمات',
    callsHandledToday: 'المكالمات التي تمت معالجتها اليوم',
    averageSatisfaction: 'متوسط الرضا',
    dashboardPlaceholder: 'ستظهر لوحة التحكم الكاملة هنا بعد التسجيل',
    assistantGuide: 'مساعد التسجيل',
    hereToHelpRegister: 'أنا هنا لمساعدتك في تسجيل شركتك',
    guideWelcome: 'مرحبًا! سأرشدك خلال عملية تسجيل شركتك.',
    guideBusinessInfo: 'أولاً، ستحتاج إلى تقديم تفاصيل شركتك مثل الاسم والعنوان ومعلومات الاتصال.',
    guideAdminAccount: 'بعد ذلك، قم بإنشاء حساب مسؤول سيكون له وصول كامل لإدارة نظام روبوت المكالمات الذكي الخاص بك.',
    guideEmployeeAccess: 'أخيرًا، يمكنك إضافة حسابات الموظفين لأعضاء الفريق الذين يحتاجون إلى الوصول إلى النظام.',
    guideCompletion: 'بمجرد الانتهاء من جميع الخطوات، سيكون لديك وصول فوري إلى لوحة تحكم روبوت المكالمات الذكي الخاص بك!',
    needHelp: 'أحتاج إلى مساعدة في حقل محدد',
    readyToStart: 'أنا مستعد للبدء',
    registrationSuccess: 'تم التسجيل بنجاح!',
    redirectingToDashboard: 'جاري التوجيه إلى لوحة التحكم الخاصة بك...'
  }
};

// Available languages with their display names and flag emojis
const availableLanguages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'ar', name: 'العربية', flag: '🇦🇪' }
];

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: () => '',
  isRTL: false,
  availableLanguages: [],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<string>(() => {
    return localStorage.getItem('language') || 'en';
  });

  const isRTL = language === 'ar';
  
  const changeLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof (typeof translations)['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: changeLanguage, 
      t, 
      isRTL,
      availableLanguages 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
