// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luaiepqxmmqlikmhyvwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1YWllcHF4bW1xbGlrbWh5dndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzM1OTYsImV4cCI6MjA2MDcwOTU5Nn0.12_TD0oHTSbjPAKK9vQWYyJKF1vKtwsdDeDrIXROtl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);